name: useragent
description: UserAgent is a dart library that parses HTTP User Agents.
version: 1.0.0
repository: https://github.com/sososdk/useragent

environment:
  sdk: ">=3.0.3 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
